### ISSUE TITLE
Close project?

### ISSUE THREAD

**Issue by smathermather** [OpenDroneMap/python-WebODM#162]
It's been a while since this project has gotten any love. It has the potential to be quite valuable, but it's been 18 months+ since we've activity on it. @rmallermartins -- is there any reason to keep this alive, or is it time to close this repo?

I am happy with either outcome, just doing a bit of housekeeping.

* python-WebODM version:
* Python version:
* Operating System:

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by pierotofy** [comment]
I would opt to archive it rather than close if there's no more interest in continuing its development. https://help.github.com/en/articles/about-archiving-repositories

**Comment by smathermather** [comment]
Ok, I'll archive it, and if we get the request, I will un-archive it. Thanks @pierotofy.
